version: "3.9"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://flasede:flasede_admin@db/flasede_db
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flasede
      - POSTGRES_PASSWORD=flasede_admin
      - POSTGRES_DB=flasede_db

volumes:
  postgres_data:
