version: "1"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=flasede_db
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
